name: Playwright CI

on:
  push:
    branches: [ main ]
  pull_request:

# Auto-cancel older runs on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test
        env:
          # Example: override base URL in CI (optional)
          BASE_URL: https://playwright.dev

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload traces & screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7

      - name: Job summary (quick links)
        if: always()
        run: |
          echo "## Playwright CI" >> $GITHUB_STEP_SUMMARY
          echo "- Report: download the **playwright-report** artifact" >> $GITHUB_STEP_SUMMARY
          echo "- Traces/screens: see **test-results** artifact (on failures)" >> $GITHUB_STEP_SUMMARY
